antminermonitor/blueprints/asicminer/models/__init__.py
from .miner import Miner
from .settings import Settings

antminermonitor/blueprints/asicminer/models/miner.py
from sqlalchemy import Column, Integer, String
from antminermonitor.database import Base

class Miner(Base):
    __tablename__ = 'miner'
    id = Column(Integer, primary_key=True)
    ip = Column(String(15), unique=True, nullable=False)
    model_id = Column(String(15), nullable=False)
    remarks = Column(String(255), nullable=True)

    def __repr__(self):
        return "Miner(ip='{}', model_id='{}', remarks='{}')" \
            .format(self.ip, self.model_id, self.remarks)

antminermonitor/blueprints/asicminer/models/settings.py
from sqlalchemy import Column, Integer, String
from antminermonitor.database import Base

class Settings(Base):
    __tablename__ = 'settings'
    id = Column(Integer, primary_key=True)
    name = Column(String(100), unique=True, nullable=False)
    value = Column(String(100), nullable=False)
    description = Column(String(255))

    def __repr__(self):
        return "Settings(name='{}', value={}, description='{}')" \
            .format(self.name, self.value, self.description)

antminermonitor/blueprints/asicminer/__init__.py
from antminermonitor.blueprints.asicminer.views.antminer import antminer
from antminermonitor.blueprints.asicminer.views.antminer_json import antminer_json

antminermonitor/blueprints/asicminer/views/antminer.py
import concurrent.futures
import re
import sys
import time
from datetime import timedelta

from flask import (Blueprint, current_app, flash, redirect, render_template,
                   request, url_for)
from flask_login import login_required
from sqlalchemy.exc import IntegrityError

from antminermonitor.blueprints.asicminer.asic_antminer import ASIC_ANTMINER
from antminermonitor.blueprints.asicminer.models import Miner
from antminermonitor.database import db_session
from config.settings import MODELS, NUM_THREADS
from lib.util_hashrate import update_unit_and_value
from lib.util_notify import notify_telegram

antminer = Blueprint('antminer', __name__, template_folder='../templates')


@antminer.route('/')
@login_required
def miners():
    # Init variables
    start = time.perf_counter()
    miners = Miner.query.all()
    active_miners = []
    inactive_miners = []

    warnings = []
    errors = []
    total_hash_rate_per_model = {}
    miner_objects = []

    # lookup table for total_hash_rate_per_model
    for id, miner in MODELS.items():
        total_hash_rate_per_model[id] = {"value": 0, "unit": miner.get('unit')}

    # create miner objects to pass to executor.map
    for miner in miners:
        module = MODELS[miner.model_id]['model_module']
        cls = MODELS[miner.model_id]['model_classname']
        obj = getattr(sys.modules[module], cls)(miner)
        miner_objects.append(obj)

    # pass this method to executor.map to poll the miner
    def poll(obj):
        obj.poll()
        return obj

    # run with ThreadPoolExecutor
    with concurrent.futures.ThreadPoolExecutor(
            max_workers=NUM_THREADS) as executor:
        results = executor.map(poll, miner_objects)
        for miner in results:
            if miner is not None:
                if miner.is_inactive:
                    inactive_miners.append(miner)
                else:
                    active_miners.append(miner)

                    for warning in miner.warnings:
                        warnings.append(warning)
                    for error in miner.errors:
                        errors.append(error)
                    total_hash_rate_per_model[
                        miner.model_id]["value"] += miner.hash_rate_ghs5s

    # Flash notifications
    if not miners:
        error_message = ("[INFO] No miners added yet. "
                         "Please add miners using the above form.")
        current_app.logger.info(error_message)
        flash(error_message, "info")
        notify_telegram(error_message)

    elif not errors:
        error_message = ("[INFO] All miners are operating normal. "
                         "No errors found.")
        current_app.logger.info(error_message)
        flash(error_message, "info")
        notify_telegram(error_message)

    for error in errors:
        current_app.logger.error(error)
        flash(error, "error")
        notify_telegram(error)

    for warning in warnings:
        current_app.logger.error(warning)
        flash(warning, "warning")
        notify_telegram(warning)

    # flash("[INFO] Check chips on your miner", "info")
    # flash("[SUCCESS] Miner added successfully", "success")
    # flash("[WARNING] Check temperatures on your miner", "warning")
    # flash("[ERROR] Check board(s) on your miner", "error")

    # Convert the total_hash_rate_per_model into a data structure that the
    # template can consume.
    total_hash_rate_per_model_temp = {}
    for key in total_hash_rate_per_model:
        value, unit = update_unit_and_value(
            total_hash_rate_per_model[key]["value"],
            total_hash_rate_per_model[key]["unit"])
        if value > 0:
            total_hash_rate_per_model_temp[key] = f"{value:3.2f} {unit}"

    end = time.perf_counter()
    loading_time = end - start
    return render_template(
        'asicminer/home.html',
        version=current_app.config['__VERSION__'],
        models=MODELS,
        errors=errors,
        warnings=warnings,
        active_miners=active_miners,
        inactive_miners=inactive_miners,
        loading_time=loading_time,
        total_hash_rate_per_model=total_hash_rate_per_model_temp)


@antminer.route('/add', methods=['POST'])
@login_required
def add_miner():
    miner_ip = request.form['ip']
    miner_model_id = request.form.get('model_id')
    miner_remarks = request.form['remarks']

    # exists = Miner.query.filter_by(ip="").first()
    # if exists:
    #    return "IP Address already added"

    add_miner(miner_ip, miner_model_id, miner_remarks)

    return redirect(url_for('antminer.miners'))


def add_miner(miner_ip, miner_model_id, miner_remarks):
    try:
        miner = Miner(ip=miner_ip,
                      model_id=miner_model_id,
                      remarks=miner_remarks)
        db_session.add(miner)
        db_session.commit()
        current_app.logger.info(
            f"Miner with IP Address {miner.ip} added successfully")
        flash(f"Miner with IP Address {miner.ip} added successfully",
              "success")
    except IntegrityError:
        db_session.rollback()
        current_app.logger.info(f"IP Address {miner.ip} already added")
        flash(f"IP Address {miner.ip} already added", "error")


@antminer.route('/discovery/', methods=['POST'])
@login_required
def miner_discovery():

    subnet = request.form.get('subnet') + "."
    start_ip = request.form.get('start_ip', type=int)
    end_ip = request.form.get('end_ip', type=int)

    if end_ip < start_ip:
        current_app.logger.error(
            f"Start IP ({start_ip}) cannot be smaller than the end IP ({end_ip})"
        )
        flash(
            f"Start IP ({start_ip}) cannot be smaller than the end IP ({end_ip})",
            "error")
        return redirect(url_for('miners'))

    supported_miner = ""
    miner_model_id = ""

    def is_pycgminer(ip):
        from lib.pycgminer import get_stats
        try:
            miner_stats = get_stats(ip)
            if miner_stats['STATUS'][0]['STATUS'] == 'error':
                current_app.logger.error("Error querying IP %s" % ip)
                flash(f"Error querying IP {ip}", "error")
                return False
        except Exception as c:
            return False
        try:
            return miner_stats['STATS'][0]['Type']
        except Exception as c:
            return False

    def add_if_supported(ip, model_id):
        # check if the miner is supported by the software
        try:
            supported_miner = [id for id in MODELS.keys() if id == model_id][0]
            add_miner(ip, supported_miner, "")
            return True
        except IndexError as i:
            return False

    while start_ip <= end_ip:
        ip = subnet + str(start_ip)
        current_app.logger.info("Querying IP %s" % ip)

        # check if is pycgminer
        miner_model_id = is_pycgminer(ip)
        if miner_model_id:
            is_supported = add_if_supported(ip, miner_model_id)
            if is_supported:
                start_ip += 1
                # TODO
                # log message of added supported miner model and IP
                continue

        # miner is not supported by the software
        current_app.logger.error(
            f"Miner with IP {ip} is currently not supported by AntminerMonitor"
        )
        flash(
            f"Miner with IP {ip} is currently not supported by AntminerMonitor",
            "info")

        start_ip += 1

    return redirect(url_for('antminer.miners'))


@antminer.route('/delete/<id>')
@login_required
def delete_miner(id):
    miner = Miner.query.filter_by(id=int(id)).first()
    if miner:
        db_session.delete(miner)
        db_session.commit()
        flash(f"Miner {miner.ip} removed successfully", "info")
    return redirect(url_for('antminer.miners'))

antminermonitor/blueprints/asicminer/views/antminer_json.py
from flask import Blueprint, jsonify
from flask_login import login_required
from lib.pycgminer import (get_summary,
                           get_pools,
                           get_stats,
                           )

antminer_json = Blueprint('antminer_json',
                          __name__,
                          template_folder='../templates',
                          )


@antminer_json.route('/<ip>/summary')
@login_required
def summary(ip):
    output = get_summary(ip)
    return jsonify(output)


@antminer_json.route('/<ip>/pools')
@login_required
def pools(ip):
    output = get_pools(ip)
    return jsonify(output)


@antminer_json.route('/<ip>/stats')
@login_required
def stats(ip):
    output = get_stats(ip)
    return jsonify(output)

antminermonitor/blueprints/asicminer/templates/asicminer/home.html
{% extends 'layouts/base.html' %}

{% block meta_description %}
Antminer Monitor, antminer, monitor, antmon, bitmain, bitcoin, litecoin, dash,
cryptocurrency, crypto, miner, mine, mining
{% endblock %}
{% block title %}Antminer Monitor {{ version }}{% endblock %}

{% block body %}
<h2>Antminer Monitor {{ version }}</h2>
<fieldset style="width: 300px;">
<legend>Countdown</legend>
<b id="countdown"></b>
</fieldset>

<div class="container">
    <div>
      <fieldset name="add">
          <legend>Add Miner</legend>
          <form action="{{ url_for('antminer.add_miner') }}" method="POST">
              <div class="addminer_container">
                  <div>
                      <label for="ip">IP Address: </label>
                  </div>
                  <div>
                      <input required type="text" name="ip" pattern="^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$" title="Please add a valid IP address (eg. xxx.xxx.xxx.xxx)" placeholder="xxx.xxx.xxx.xxx">
                  </div>
                  <div>
                      <label for="model_id">Model: </label>
                  </div>
                  <div>
                      <select required name="model_id">
                          <option disabled selected value> -- select an option --</option>
                          {%- for id, model in models.items() %}
                              <option value="{{ id }}">{{ model.get('description') }}</option>
                          {%- endfor %}
                      </select>
                  </div>
                  <div>
                      <label for="remarks">Remarks: </label>
                  </div>
                  <div>
                      <input type="text" name="remarks">
                  </div>
                  <p><input type="submit" value="Add model"></p>
              </div>
          </form>
      </fieldset>
    </div>
    <div>
        <fieldset name="miner_discovery">
            <legend>Miner Discovery</legend>
            <form action="{{ url_for('antminer.miner_discovery') }}" method="POST">
                <div class="minerdiscovery_container">
                    <div>
                        <label for="subnet">Subnet: </label>
                    </div>
                    <div>
                        <input required type="text" name="subnet" pattern="^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){2}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$" title="Please add a valid network subnet (eg. xxx.xxx.xxx)" placeholder="xxx.xxx.xxx">
                    </div>
                    <div>
                        <label for="start_ip">Start IP: </label>
                    </div>
                    <div>
                        <input required type="number" name="start_ip" min="1" max="255" title="Accepted value: 1-255">
                    </div>
                    <div>
                        <label for="end_ip">End IP: </label>
                    </div>
                    <div>
                        <input required type="number" name="end_ip"  min="1" max="255" title="Accepted value: 1-255">
                    </div>
                    <p><input type="submit" value="Discover"></p>
                </div>
            </form>
        </fieldset>
    </div>
    <div></div>
    <div>
        <fieldset name="total_hashrate" style="height:130px">
            <legend>Total hashrate per model (5s)</legend>
            <ul>
                {%- for model in total_hash_rate_per_model|sort %}
                    <li><u>{{ model }}:</u> <strong>{{ total_hash_rate_per_model[model] }}</strong>
                    </li>
                {%- endfor %}
            </ul>
        </fieldset>
    </div>
</div>
<br>

{%- with messages = get_flashed_messages(with_categories=true) %}
    {%- if messages %}
        {%- for category, message in messages %}
            <div class="{{ category }}">
                <strong>{{ message }}</strong>
            </div>
        {%- endfor %}
    {%- endif %}
{%- endwith %}
<br>

{%- if inactive_miners %}
    <fieldset name="inactive_miner_list">
        <legend>In-active Miners ({{ inactive_miners|length }})</legend>
        <table style="width:100%">
            <tr>
                <th>IP Address</th>
                <th>Model</th>
                <th>Remarks</th>
                <th>Status</th>
                <th>Remove</th>
            </tr>
            {%- for inactive_miner in inactive_miners|sort(attribute='ip') %}
                <tr>
                    <td><a target="_blank" href="http://{{ inactive_miner.ip }}/cgi-bin/minerStatus.cgi">{{ inactive_miner.ip }}</a></td>
                    <td>{{ inactive_miner.model_id }}</td>
                    <td>{{ inactive_miner.remarks }}</td>
                    <!-- <td>Error: Check connection or IP Address</td> -->
                    <td>{{ inactive_miner.errors }}</td>
                    <td><a href={{ url_for('antminer.delete_miner', id=inactive_miner.id) }} style="text-decoration:none">&#10060;</a></td>
                </tr>
            {%- endfor %}
        </table>
    </fieldset>
{%- endif %}
<br>

<fieldset name="active_miner_list">
    <legend>Active Miners ({{ active_miners|length }})</legend>
    <table style="width:100%">
        <tr>
            <th>IP Address</th>
            <th>Worker</th>
            <th>Model</th>
            <th>Remarks</th>
            <th title="'O' means OK">Chips (Os)</th>
            <th title="'X' means defective">Chips (Xs)</th>
            <th title="'-' means instability of the power supply voltage or the defective hash board">Chips (-)</th>
            <th>Chip Temp(C)</th>
            <th>Fan speeds (rpm)</th>
            <th>Hashrate (5s)</th>
            <th>HW Error Rate %</th>
            <th>Uptime</th>
            <th>Status</th>
            <!--<th>JSON Info</th>-->
            <th>Remove</th>
        </tr>
        {%- for active_miner in active_miners|sort(attribute='ip') %}
            <tr {%- if active_miner.errors %} class="error"{%- endif %}>
                <td><a target="_blank" href="http://{{ active_miner.ip }}/cgi-bin/minerStatus.cgi">{{ active_miner.ip }}</a></td>
                <td>{{ active_miner.worker }}</td>
                <td title="{{ models.get(active_miner.model_id).get('description') }}">{{ active_miner.model_id }}</td>
                <td>{{ active_miner.remarks }}</td>
                <td>{{ active_miner.chips['Os'] }}</td>
                <td>{{ active_miner.chips['Xs'] }}</td>
                <td>{{ active_miner.chips['-'] }}</td>
                <td>{{ active_miner.temperatures }}</td>
                <td>{{ active_miner.fan_speeds }}</td>
                <td>{{ active_miner.normalized_hash_rate }}</td>
                <td>{{ active_miner.hw_error_rate }}</td>
                <td>{{ active_miner.uptime }}</td>
                <td title="{%- if active_miner.errors %}{{ active_miner.errors }}{%- else %}OK{%- endif %}">
                    {%- if active_miner.errors %}Check your miner{%- else %}OK{%- endif %}</td>
                <!--<td><a target="_blank" href="/{{ active_miner.ip }}/summary">Summary</a> |
                    <a target="_blank" href="/{{ active_miner.ip }}/pools">Pools</a> |
                    <a target="_blank" href="/{{ active_miner.ip }}/stats">Stats</a></td>-->
                <td><a href={{ url_for('antminer.delete_miner', id=active_miner.id) }} style="text-decoration:none">&#10060;</a></td>
            </tr>
        {%- endfor %}
    </table>
</fieldset>
{% endblock %}

{% block tail_js -%}
{{ super() -}}
    <script src="{{ url_for('static', filename='scripts/main.js') }}"></script>
{% endblock -%}