antminermonitor/blueprints/user/models.py
from flask_login.mixins import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from sqlalchemy import Column, Integer, VARCHAR
from antminermonitor.database import Base


class User(UserMixin, Base):
    __tablename__ = 'user'
    id = Column(Integer, primary_key=True)
    username = Column(VARCHAR(64), index=True, unique=True)
    email = Column(VARCHAR(120), index=True, unique=True)
    password_hash = Column(VARCHAR(128))
    surname = Column(VARCHAR(100))
    firstname = Column(VARCHAR(100))
    active = Column(Integer, default=1)

    @property
    def serialize(self):
        return {
            'id': self.id,
            'username': self.username,
            'firstname': self.firstname,
            'surname': self.surname,
            'email': self.email
        }

    def __repr__(self):
        return '<User {}>'.format(self.username)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

antminermonitor/blueprints/user/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, PasswordField, SelectField, StringField
from wtforms.validators import EqualTo, Length


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[Length(min=5, max=64)])
    password = PasswordField(
        'Password', validators=[
            Length(min=6, max=128),
        ])
    remember = BooleanField('Remember me')


class PasswordResetForm(FlaskForm):
    # username = TextField('Username', validators=[Length(min=5, max=64)])
    username = SelectField('Username')
    password = PasswordField(
        'New Password',
        validators=[
            Length(min=6, max=128),
            EqualTo('confirm', message='Passwords must match')
        ])
    confirm = PasswordField('Repeat Password')

antminermonitor/blueprints/user/__init__.py
from antminermonitor.blueprints.user.views import user

antminermonitor/blueprints/user/views.py
from flask import (Blueprint, abort, flash, redirect, render_template, request,
                   session, url_for)
from flask_login import current_user, login_required, login_user, logout_user
from werkzeug.security import check_password_hash

from antminermonitor.blueprints.user.forms import LoginForm, PasswordResetForm
from antminermonitor.blueprints.user.models import User
from antminermonitor.database import db_session
from lib.util_url import is_safe_url

user = Blueprint('user', __name__, template_folder='templates')


@user.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user:
            if check_password_hash(user.password_hash, form.password.data):
                print(form.remember.data)
                login_user(user, remember=form.remember.data)
                if 'next' in session:
                    next = session['next']
                    if is_safe_url(next):
                        return redirect(next)
                return redirect(url_for('antminer.miners'))
        flash("[ERROR] Invalid username or password", "error")
        return render_template('user/login.html', form=form)

    if current_user.is_authenticated:
        return redirect(url_for('antminer.miners'))

    return render_template('user/login.html', form=form)


@user.route('/password_update', methods=['GET', 'POST'])
@login_required
def password_update():
    form = PasswordResetForm()
    form.username.choices = [(u.username, u.username)
                             for u in User.query.all()]
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user:
            password = form.password.data
            user.set_password(password)
            db_session.commit()
            flash(
                "[INFO] Password updated for user '{}'".format(user.username),
                "info")
            next = request.args.get('next')
            if not is_safe_url(next):
                abort(400)
            return redirect(next or url_for('user.password_update'))
        flash("[ERROR] User '{}' does not exist".format(form.username.data),
              "error")
        return render_template('user/password_update.html', form=form)

    return render_template('user/password_update.html', form=form)


@user.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('antminer.miners'))

antminermonitor/blueprints/user/templates/user/login.html
{% extends "layouts/base.html" %}
{% block head_css %}
    {{ super() -}}
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/login.css') }}">

    <style>
    div .loginform {
        position: relative;
        top: 30%;
        left: 50%;
        margin-top: -50px;
        margin-left: -50px;
        width: 100px;
        //height: 100px;
        //background: red;
    }
    </style>
    
    {% endblock %}
{% block body %}
    <br><br><br><br>
    <fieldset class="loginform">
    <div>
        <form method="post" action="{{ url_for('user.login') }}">            
        {%- with messages = get_flashed_messages(with_categories=true) %}
            {%- if messages %}
                {%- for category, message in messages %}
                    <div class="{{ category }}">
                        <strong>{{ message }}</strong>
                    </div>
                {%- endfor %}
            {%- endif %}
        {%- endwith %}
            <h2 class="form-signin-heading">Login</h2>
            {{ form.hidden_tag() }}
	    {{ form.username.label }}<br>
	    {{ form.username(class="form-control", placeholder="Username", required="", autofocus="") }}<br>
            {% for error in form.username.errors %}
	    <span style="color: red;">[{{ error }}]</span><br>
            {% endfor %}
	    <br>
	    {{ form.password.label }}<br>
	    {{ form.password(class="form-control", placeholder="Password", required="") }}<br>
            {% for error in form.password.errors %}
	    <span style="color: red;">[{{ error }}]</span><br>
            {% endfor %}
	    <br>
	    {{ form.remember() }} {{ form.remember.label }}<br><br>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        </form>
    </div>
    </legend>
{% endblock %}

antminermonitor/blueprints/user/templates/user/password_update.html
{% extends "layouts/base.html" %}
{% block head_css %}
    {{ super() -}}
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/login.css') }}">

    <style>
    div .loginform {
        position: relative;
        top: 30%;
        left: 50%;
        margin-top: -50px;
        margin-left: -50px;
        width: 100px;
        //height: 100px;
        //background: red;
    }
    </style>
    
    {% endblock %}
{% block body %}
    <br><br><br><br>
    <fieldset class="loginform">
    <div>
        <form method="post" action="{{ url_for('user.password_update') }}">
        {%- with messages = get_flashed_messages(with_categories=true) %}
            {%- if messages %}
                {%- for category, message in messages %}
                    <div class="{{ category }}">
                        <strong>{{ message }}</strong>
                    </div>
                {%- endfor %}
            {%- endif %}
        {%- endwith %}
            <h2 class="form-signin-heading">Password Update</h2>
            {{ form.hidden_tag() }}
	    {{ form.username.label }}<br>
	    {{ form.username(class="form-control", required="", autofocus="") }}<br>
            {% for error in form.username.errors %}
	    <span style="color: red;">[{{ error }}]</span><br>
            {% endfor %}
	    <br>
	    {{ form.password.label }}<br>
	    {{ form.password(class="form-control", placeholder="New Password", required="") }}<br>
            {% for error in form.password.errors %}
	    <span style="color: red;">[{{ error }}]</span><br>
            {% endfor %}
	    <br>
	    {{ form.confirm.label }}<br>
	    {{ form.confirm(class="form-control", placeholder="Repeat Password", required="") }}<br>
            {% for error in form.confirm.errors %}
	    <span style="color: red;">[{{ error }}]</span><br>
            {% endfor %}
	    <br>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Update Password</button>
        </form>
    </div>
    </fieldset>
{% endblock %}